---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: local

verifier:
  name: terraform
  systems:
    - name: system
      backend: local
      attrs:
        - test/integration/attributes/attrs.yml

suites:
  - name: aws_chef_server
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/aws
